name: CI
on:
  pull_request:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install poetry
      - run: poetry install
      - run: poetry run black --check .
      - run: poetry run isort --check .
      - run: poetry run flake8
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install poetry
      - run: poetry install
      - run: poetry run pytest --cov=./ --cov-report=xml
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml
  docker-build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "IMAGE=ghcr.io/org/${{ github.event.repository.name }}:${{ github.sha }}" >> $GITHUB_ENV
      - run: docker build -t $IMAGE -f infra/docker/Dockerfile .
      - run: docker push $IMAGE
      - uses: actions/upload-artifact@v3
        with:
          name: image
          path: /tmp
